nginx:
  build: nginx
  restart: no
  ports:
    - "80:80"
    - "443:443"
  links:
    - stash
    - jira
    - confluence
    - crowd

stash:
  build: atlassian-stash
  restart: no
  ports:
    - "7990:7990" # no cache
    - "7999:7999" # ssh port
  links:
    - database
  volumes:
    - atlassian-stash/home:/opt/stash-home

jira:
  build: atlassian-jira
  restart: no
  ports:
    - "8080:8080" # no cache
  links:
    - database
  volumes:
    - atlassian-jira/home:/opt/jira-home

confluence:
  build: atlassian-confluence
  restart: no
  ports:
    - "8090:8090" # no cache
  links:
    - database
  volumes:
    - atlassian-confluence/home:/opt/confluence-home

crowd:
  build: atlassian-crowd
  restart: no
  ports:
    - "8095:8095" # no cache
  links:
    - database
  volumes:
    - atlassian-crowd/home:/opt/crowd-home

database:
  image: postgres:9.4
  restart: no
  volumes:
    - postgres/initdb:/docker-entrypoint-initdb.d
    - tmp:/tmp # import backups
