nginx:
  image: nginx:1.9
  restart: always
  ports:
    - "80:80"
    - "443:443"
  links:
    - stash
    - jira
    - confluence
    - crowd
  volumes:
    - nginx.conf:/etc/nginx/nginx.conf

stash:
  extends:
    file: atlassian-stash/stash.yml
    service: stash
  restart: always
  links:
    - database
  volumes:
    - atlassian-stash/home:/opt/stash-home

jira:
  extends:
    file: atlassian-jira/jira.yml
    service: jira
  restart: always
  links:
    - database
  volumes:
    - atlassian-jira/home:/opt/jira-home

confluence:
  extends:
    file: atlassian-confluence/confluence.yml
    service: confluence
  restart: always
  links:
    - database
  volumes:
    - atlassian-confluence/home:/opt/confluence-home

crowd:
  extends:
    file: atlassian-crowd/crowd.yml
    service: crowd
  restart: always
  links:
    - database
  volumes:
    - atlassian-crowd/home:/opt/crowd-home

database:
  image: postgres:9.4
  restart: always
  volumes:
    - data:/var/lib/postgresql/data
    - atlassian-confluence/setup-confluence-db.sh:/docker-entrypoint-initdb.d/setup-confluence-db.sh
    - atlassian-crowd/setup-crowd-db.sh:/docker-entrypoint-initdb.d/setup-crowd-db.sh
    - atlassian-jira/setup-jira-db.sh:/docker-entrypoint-initdb.d/setup-jira-db.sh
    - atlassian-stash/setup-stash-db.sh:/docker-entrypoint-initdb.d/setup-stash-db.sh
    - tmp:/tmp # import backups
