stash:
  extends:
    file: stash.yml
    service: stash
  ports:
    - "80:7990"
    - "22:7999"
  links:
    - database
  volumes:
    - home:/opt/stash-home

database:
  image: postgres:9.4
  volumes:
    - setup-stash-db.sh:/docker-entrypoint-initdb.d/setup-stash-db.sh
