crowd:
  extends:
    file: crowd.yml
    service: crowd
  links:
    - database
  volumes:
    - home:/opt/crowd-home

database:
  image: postgres:9.4
  volumes:
    - setup-crowd-db.sh:/docker-entrypoint-initdb.d/setup-crowd-db.sh
